### PR TITLE
新增了GUI代码，并把功能模块化

### PR DESCRIPTION
**Pull request by Chizukuo**
image

### CODE REVIEW

**Comment by cyanire** [comment]
epic

**Comment by cyanire** [comment]
@Chizukuo Can we pack them into a .exe file or is there a better way to run the code from mobile platforms?

**Comment by Chizukuo** [comment]
> @Chizukuo Can we pack them into a .exe file or is there a better way to run the code from mobile platforms?

The .exe file is located in the release section of my forked repository. I’m considering porting it to the Android platform, but with so much effort required recently, it’s university exam week.

**Comment by cyanire** [comment]
> > @Chizukuo Can we pack them into a .exe file or is there a better way to run the code from mobile platforms?
> 
> The .exe file is located in the release section of my forked repository. I’m considering porting it to the Android platform, but with so much effort required recently, it’s university exam week.

understood, thanks for your contribution ❤️

**Pull request merged**
